services:

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.https.conf:/etc/nginx/conf.d/default.conf:ro
      - ${RUNTIME_DIR}/certbot/conf:/etc/letsencrypt:ro
      - ${RUNTIME_DIR}/certbot/www:/var/www/certbot:ro
    volumes_from:
      - php:ro

  php:
   volumes:
     - ${RUNTIME_DIR}/wordpress:/var/www/html

  certbot:
    image: certbot/certbot
    container_name: wp-certbot
    volumes:
     - ${RUNTIME_DIR}/certbot/conf:/etc/letsencrypt
     - ${RUNTIME_DIR}/certbot/www:/var/www/certbot
    networks:
      - wp-network
    profiles:
     - tools

  certbot-renew:
    image: certbot/certbot
    container_name: wp-certbot-renew
    volumes:
     - ${RUNTIME_DIR}/certbot/conf:/etc/letsencrypt
     - ${RUNTIME_DIR}/certbot/www:/var/www/certbot
    networks:
      - wp-network
    entrypoint: >
      /bin/sh -c
      "trap exit TERM;
       while :; do
         certbot renew;
         sleep 12h & wait $${!};
       done"

  backup:
    build: ./backup
    container_name: backup-service
    depends_on:
      - mysql
    volumes:
      - wordpress_data:/var/www/html/wp-content
      - backup_data:/backup
    networks:
      - wp-network
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      S3_BUCKET: ${S3_BUCKET}
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - wp-network

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - wp-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - wp-network
    restart: unless-stopped

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    volumes:
      - ./monitoring/.my.cnf:/home/exporter/.my.cnf:ro
    # IMPORTANTE: Indicamos al exportador que use ese archivo
    command:
      - "--config.my-cnf=/home/exporter/.my.cnf"
    depends_on:
      - mysql
    ports:
      - "9104:9104"
    networks:
      - wp-network
