name: Deploy to EC2

on:
  push:
    branches:
      - main
      - dev

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 2222

        script: |
          set -e
          cd ~/projecto-devops/repo/wordpress-docker-devops

          echo "Reset repo"
          git fetch origin
          git reset --hard origin/main
          git clean -fd

          echo "Deploy stack"
          make up-prod ENV=prod
